name: Python CI for Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Supports Python 3.8+ and is future-ready

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5   # ✅ updated version
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 and pytest
        run: |
          source venv/bin/activate
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator  # ✅ Replace 'calculator' with your actual module
