name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run linter and tests
    - name: Run flake8 and pytest
      run: |
        source venv/bin/activate
        flake8 --exclude=venv* --statistics
        pytest -v --cov=calculator
